version: "3.9"

services:
  app:
    build: .
    command: sh /code/scripts/run_uvicorn.sh
    volumes:
      - .:/code
    ports:
      - 8000:8000
    env_file:
      .env

networks:
  default:
    name: app-network
    external: true