version: "3.9"

services:
  db:
    image: bitnami/postgresql:13.6.0
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdbdata:/bitnami/postgresql

volumes:
  pgdbdata:

networks:
  default:
    name: app-network
    external: true
